# Generated by Django 4.2.2 on 2023-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[{'pizza', '1'}, {'2', 'burger'}, {'pasta', '3'}, {'4', 'fries'}], max_length=6)),
                ('image', models.ImageField(upload_to='food_img/')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=105)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
