# Generated by Django 4.2.2 on 2023-06-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('pizza', 'pizza'), ('burger', 'burger'), ('pasta', 'pasta'), ('fries', 'fries')], max_length=6),
        ),
    ]
